### ISSUE TITLE
Interesting Project!

### ISSUE THREAD

**Issue by nicksarafa** [Defi-Time/White-Paper#1]
Elijah from Solana Breakpoint turned me on to your project! I believe there's a huge opportunity in the blockchain booking space. Excited to follow the project! Thanks for sharing the white paper!

**Comment by mim-Armand** [comment]
Thanks, Nick @nicksarafa for your kind words, we will get back to the project soon and hopefully have more updates coming up.
Got a bit busy with work and end-of-year stuff.
We are looking for developers to join our team btw, let us know if you're interested.

Thanks again and have a great weekend
